name: ${project.parent.name}
main: me.kevinnovak.livecoordinates.LiveCoordinates
version: ${project.parent.version}
author: KevinNovak
description: ${project.parent.description}
api-version: 1.13

permissions:
  livecoordinates.display:
    description: Allowed to see live coordinates.
    default: true
